### ISSUE TITLE
Images example

### ISSUE THREAD

**Issue by dtruffaut** [drufball/layered-apis#13] opened 2018-04-30 18:26 UTC
Examples should include columns or rows of images. Each image can have a different width and/or height.

Pinterest-like
In vertical-columns mode, each image width is bound to the column's width, but the height of each image varies. Make and example with 3 columns.

Optional :
In horizontal rows mode, each image height is bound to the row's height, but the width of each image varies. Useful for on mobile to display for example content of a cart (bought items), or facets with images (see horizontal facets ala Google or Pinterest)

Padding, margin and borders can be defined.

Images are an example, but it should work with every object that have an undetermined width and/or height.

Some items must be loaded forward or backward to ensure fluidity at 60 FPS.

Provide an example with picture / source element on which srcset and sizes attributes are set, each source having a different format (at least, image/webp and image/jpg), thus a low resolution image loading before the hd one, so the LQIP pattern is properly handled.

Please.

That's what we need.

**Comment by domenic** [comment] 2018-04-30 18:38
I can't understand what the issue is here. Can you point to a part of the explainer or spec that seems to have a bug? Otherwise, if you are asking for help on building your web site, this is not the appropriate place.

Let me close this as it seems off-topic. If we can figure out the actual bug report I'll be happy to reopen.

**Closed by domenic** 2018-04-30 18:38 UTC
